function S = pocketlabSensorRegistry()
%POCKETLABSENSORREGISTRY Internal Voyager 2 single-sensor registry.
%
% Config values and value lengths are from the public pocketlab-bluetooth
% Voyager 2 device configuration. Only acceleration has been physically
% validated with this MATLAB driver so far.
%
% Units for unvalidated sensors are intentionally left as "native" until
% verified experimentally or from a decoder implementation.

mk = @(displayName,configValue,valueLength,nch,labels,unit,validated) ...
    struct('DisplayName',string(displayName), ...
           'ConfigValue',uint32(configValue), ...
           'ValueLength',double(valueLength), ...
           'NumChannels',double(nch), ...
           'Labels',string(labels), ...
           'Unit',string(unit), ...
           'Validated',logical(validated));

S = struct;

S.acceleration = mk("Acceleration XYZ",112,12,3, ...
    ["ax","ay","az"],"g",true);

S.gyroscope = mk("Gyroscope XYZ",896,12,3, ...
    ["gx","gy","gz"],"native",false);

S.magnetometer = mk("Magnetometer XYZ",7168,12,3, ...
    ["mx","my","mz"],"native",false);

S.heading = mk("Heading",8192,4,1,"heading","native",false);
S.pitch   = mk("Pitch",16384,4,1,"pitch","native",false);
S.roll    = mk("Roll",32768,4,1,"roll","native",false);

S.quaternion = mk("Quaternion",65536,16,4, ...
    ["q1","q2","q3","q4"],"native",false);

S.rangefinder = mk("Rangefinder",16777216,4,1, ...
    "range","native",false);

S.displacement = mk("Rangefinder Displacement",1,4,1, ...
    "displacement","native",false);

S.velocity = mk("Rangefinder Velocity",2,4,1, ...
    "velocity","native",false);

S.rangeacceleration = mk("Rangefinder Acceleration",8,4,1, ...
    "acceleration","native",false);

S.external = mk("External Sensor",131072,4,1, ...
    "external","native",false);

S.temperature = mk("Temperature",262144,4,1, ...
    "temperature","native",false);

S.pressure = mk("Pressure",524288,4,1, ...
    "pressure","native",false);

S.humidity = mk("Humidity",1048576,4,1, ...
    "humidity","native",false);

S.altitude = mk("Altitude",2097152,4,1, ...
    "altitude","native",false);

S.dewpoint = mk("Dew Point",4194304,4,1, ...
    "dewpoint","native",false);

S.heatindex = mk("Heat Index",8388608,4,1, ...
    "heatindex","native",false);

S.uvlight = mk("UV Light",33554432,4,1, ...
    "uvlight","native",false);

S.ambientlight = mk("Ambient Light",67108864,4,1, ...
    "ambientlight","native",false);

S.irlight = mk("IR Light",134217728,4,1, ...
    "irlight","native",false);
end
